const columnsStructure = [
    [
        {
            title: 'Customer ID',
            dataIndex: 'customerID',
            width: 150,
            sorter: (a, b) => a.customerID > b.customerID,
            sortDirections: ['ascend'],
        },
        {
            title: 'Company Name',
            dataIndex: 'companyName',
            width: 150,
            sorter: (a, b) => a.companyName > b.companyName,
            sortDirections: ['ascend'],
        },
        {
            title: 'Contact Name',
            dataIndex: 'contactName',
            width: 150,
            sorter: (a, b) => a.contactName > b.contactName,
            sortDirections: ['ascend'],
        },
        {
            title: 'Contact Title',
            dataIndex: 'contactTitle',
            width: 150,
            sorter: (a, b) => a.contactTitle > b.contactTitle,
            sortDirections: ['ascend'],
        },
        {
            title: 'City',
            dataIndex: 'city',
            width: 150,
            sorter: (a, b) => a.city > b.city,
            sortDirections: ['ascend'],
        },
        {
            title: 'Region',
            dataIndex: 'region',
            width: 150,
            sorter: (a, b) => a.region > b.region,
            sortDirections: ['ascend'],
        },
        {
            title: 'PostalCode',
            dataIndex: 'postalCode',
            width: 150,
            sorter: (a, b) => a.postalCode > b.postalCode,
            sortDirections: ['ascend'],
        },
        {
            title: 'Country',
            dataIndex: 'country',
            width: 150,
            sorter: (a, b) => a.country > b.country,
            sortDirections: ['ascend'],
        },
        {
            title: 'Phone',
            dataIndex: 'phone',
            width: 150,
            sorter: (a, b) => a.phone > b.phone,
            sortDirections: ['ascend'],
        },
    ],
    [
        {
            title: 'Product ID',
            dataIndex: 'productID',
            width: 150,
            sorter: (a, b) => a.productID > b.productID,
            sortDirections: ['ascend'],
        },
        {
            title: 'Supplier ID',
            dataIndex: 'supplierID',
            width: 150,
            sorter: (a, b) => a.supplierID > b.supplierID,
            sortDirections: ['ascend'],
        },
        {
            title: 'Category ID',
            dataIndex: 'categoryID',
            width: 150,
            sorter: (a, b) => a.categoryID > b.categoryID,
            sortDirections: ['ascend'],
        },
        {
            title: 'Quantity Per Unit',
            dataIndex: 'quantityPerUnit',
            width: 150,
            sorter: (a, b) => a.quantityPerUnit > b.quantityPerUnit,
            sortDirections: ['ascend'],
        },
        {
            title: 'Unit Price',
            dataIndex: 'unitPrice',
            width: 150,
            sorter: (a, b) => a.unitPrice > b.unitPrice,
            sortDirections: ['ascend'],
        },
        {
            title: 'Units In Stock',
            dataIndex: 'unitsInStock',
            width: 150,
            sorter: (a, b) => a.unitsInStock > b.unitsInStock,
            sortDirections: ['ascend'],
        },
        {
            title: 'Units On Order',
            dataIndex: 'unitsOnOrder',
            width: 150,
            sorter: (a, b) => a.unitsOnOrder > b.unitsOnOrder,
            sortDirections: ['ascend'],
        },
        {
            title: 'Reorder Level',
            dataIndex: 'reorderLevel',
            width: 150,
            sorter: (a, b) => a.reorderLevel > b.reorderLevel,
            sortDirections: ['ascend'],
        },
        {
            title: 'Discontinued',
            dataIndex: 'discontinued',
            width: 150,
            sorter: (a, b) => a.discontinued > b.discontinued,
            sortDirections: ['ascend'],
        },
        {
            title: 'Name',
            dataIndex: 'name',
            width: 150,
            sorter: (a, b) => a.name > b.name,
            sortDirections: ['ascend'],
        },
    ],
    [
        {
            title: 'Order ID',
            dataIndex: 'orderID',
            width: 150,
            sorter: (a, b) => a.orderID > b.orderID,
            sortDirections: ['ascend'],
        },
        {
            title: 'Product ID',
            dataIndex: 'productID',
            width: 150,
            sorter: (a, b) => a.productID > b.productID,
            sortDirections: ['ascend'],
        },
        {
            title: 'Unit Price',
            dataIndex: 'unitPrice',
            width: 150,
            sorter: (a, b) => a.unitPrice > b.unitPrice,
            sortDirections: ['ascend'],
        },
        {
            title: 'Quantity',
            dataIndex: 'quantity',
            width: 150,
            sorter: (a, b) => a.quantity > b.quantity,
            sortDirections: ['ascend'],
        },
        {
            title: 'Discount',
            dataIndex: 'discount',
            width: 150,
            sorter: (a, b) => a.discount > b.discount,
            sortDirections: ['ascend'],
        },
    ],
]

export default columnsStructure;